export { applyCatalogSelection } from "./catalogSelection";
export * as tauri from "./tauri";
export {
  getProfile,
  saveProfile,
  getDeviceInfo,
  getConnected,
  isDeviceConnected,
  getLastReport,
  getPermissionStatus,
  requestPermission,
  openAccessibilitySettings,
  openInputMonitoringSettings,
  relaunchApp,
  listInstalledApps,
  openPath,
  openUrl,
  buttonCatalog,
  CAPTURE_SESSION_OFF,
  applyCaptureSession,
  setKeyCapture,
  setActivatorCapture,
  setComboActivatorCapture,
  setComboTriggerCapture,
  setUiModal,
  getAppIcon,
  resetTccPermissions,
  autostartIsEnabled,
  autostartSet,
} from "./tauri";
