import type { ActionCategoryId } from "../../types/index";
import type { Lang } from "../../i18n/types";

export const CATEGORY_ORDER: ActionCategoryId[] = [
  "basic",
  "mouse",
  "browser",
  "edit",
  "keys",
  "system",
  "media",
  "launch",
  "custom",
];

export const CATEGORY_LABELS: Record<Lang, Record<ActionCategoryId, string>> = {
  ko: {
    basic: "기본",
    mouse: "마우스",
    browser: "브라우저",
    edit: "편집",
    keys: "키",
    system: "창 · 시스템",
    media: "미디어",
    launch: "실행",
    custom: "커스텀",
  },
  en: {
    basic: "Basic",
    mouse: "Mouse",
    browser: "Browser",
    edit: "Edit",
    keys: "Keys",
    system: "Window · System",
    media: "Media",
    launch: "Launch",
    custom: "Custom",
  },
};

export const ENTRY_LABELS: Record<Lang, Record<string, string>> = {
  ko: {
    default: "OS 기본",
    disabled: "끄기",
    mouse_left: "왼쪽 클릭",
    mouse_right: "오른쪽 클릭",
    mouse_middle: "가운데 클릭",
    mouse_back: "뒤로 (마우스)",
    mouse_forward: "앞으로 (마우스)",
    double_click: "두 번 클릭",
    scroll_left: "왼쪽 스크롤",
    scroll_right: "오른쪽 스크롤",
    safari_back: "Safari: 뒤로",
    safari_forward: "Safari: 앞으로",
    safari_zoom_in: "Safari: 확대",
    safari_zoom_out: "Safari: 축소",
    copy: "복사 (⌘C)",
    cut: "잘라내기 (⌘X)",
    paste: "붙여넣기 (⌘V)",
    undo: "실행 취소 (⌘Z)",
    redo: "다시 실행 (⇧⌘Z)",
    save: "저장 (⌘S)",
    return: "Enter/Return",
    esc: "Esc",
    tab: "Tab",
    delete: "Delete",
    mission_control: "Mission Control",
    move_space_left: "이전 데스크탑",
    move_space_right: "다음 데스크탑",
    app_expose: "App Exposé",
    show_desktop: "데스크탑 보기",
    launchpad: "앱 보기",
    spotlight: "Spotlight",
    app_switcher: "응용 프로그램 전환",
    close_window: "창 닫기",
    volume_up: "음량 높이기",
    volume_down: "음량 낮추기",
    mute: "음소거",
    previous_track: "이전 트랙",
    next_track: "다음 트랙",
    play_pause: "재생/일시정지",
    open_safari: "Safari 열기",
    open_finder: "Finder",
    open_settings: "시스템 설정",
    open_app_pick: "앱 열기…",
    custom_key: "커스텀",
    macro: "매크로 입력",
  },
  en: {
    default: "OS default",
    disabled: "Off",
    mouse_left: "Left click",
    mouse_right: "Right click",
    mouse_middle: "Middle click",
    mouse_back: "Back (mouse)",
    mouse_forward: "Forward (mouse)",
    double_click: "Double click",
    scroll_left: "Scroll left",
    scroll_right: "Scroll right",
    safari_back: "Safari: Back",
    safari_forward: "Safari: Forward",
    safari_zoom_in: "Safari: Zoom in",
    safari_zoom_out: "Safari: Zoom out",
    copy: "Copy (⌘C)",
    cut: "Cut (⌘X)",
    paste: "Paste (⌘V)",
    undo: "Undo (⌘Z)",
    redo: "Redo (⇧⌘Z)",
    save: "Save (⌘S)",
    return: "Enter/Return",
    esc: "Esc",
    tab: "Tab",
    delete: "Delete",
    mission_control: "Mission Control",
    move_space_left: "Previous desktop",
    move_space_right: "Next desktop",
    app_expose: "App Exposé",
    show_desktop: "Show Desktop",
    launchpad: "Apps",
    spotlight: "Spotlight",
    app_switcher: "App switcher",
    close_window: "Close window",
    volume_up: "Volume up",
    volume_down: "Volume down",
    mute: "Mute",
    previous_track: "Previous track",
    next_track: "Next track",
    play_pause: "Play/Pause",
    open_safari: "Open Safari",
    open_finder: "Finder",
    open_settings: "System Settings",
    open_app_pick: "Open app…",
    custom_key: "Custom",
    macro: "Macro input",
  },
};
